tinkoff:
  apiUrl: 'https://api-invest.tinkoff.ru/openapi'
  apiUrlSandbox: 'https://api-invest.tinkoff.ru/openapi/sandbox'
  socketURL: 'wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws'
  secretToken: ''
  sandboxToken: ''
